// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_level_five_master = "CgkIzczH8PQNEAIQBw"; // <GPGSID>
        public const string achievement_level_nine_master = "CgkIzczH8PQNEAIQCw"; // <GPGSID>
        public const string achievement_tutorial_master = "CgkIzczH8PQNEAIQAg"; // <GPGSID>
        public const string achievement_level_eight_master = "CgkIzczH8PQNEAIQCg"; // <GPGSID>
        public const string achievement_level_seven_master = "CgkIzczH8PQNEAIQCQ"; // <GPGSID>
        public const string achievement_level_four_master = "CgkIzczH8PQNEAIQBg"; // <GPGSID>
        public const string achievement_level_six_master = "CgkIzczH8PQNEAIQCA"; // <GPGSID>
        public const string achievement_level_one_master = "CgkIzczH8PQNEAIQAw"; // <GPGSID>
        public const string achievement_level_two_master = "CgkIzczH8PQNEAIQBA"; // <GPGSID>
        public const string achievement_level_three_master = "CgkIzczH8PQNEAIQBQ"; // <GPGSID>

}

